config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"

  get 'courses/new'
  get 'courses/edit'
  get 'courses/show'
  get 'courses/index'

  get 'instructors/new'
  get 'instructors/edit'
  get 'instructors/index'
  get 'instructors/show'

  get 'cohorts/new'
  get 'cohorts/edit'
  get 'cohorts/index'
  get 'cohorts/show'

  get 'admins/new'
  get 'admins/edit'
  get 'admins/show'
  get 'admins/index'

  get 'tests/new'
  get 'tests/edit'
  get 'tests/show'
  get 'tests/index'

  get 'students/new'
  get 'students/edit'
  get 'students/show'
  get 'students/index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :admins

  resources :students do
    delete 'terminate' => 'students#destroy'
  end

  resources :instructors do
    delete 'terminate' => 'students#destroy'
  end

  resources :cohorts do
    delete 'terminate' => 'cohorts#destroy'
  end

  resources :courses do
    delete 'terminate' => 'courses#destroy'
  end

  resources :cohorts do
    resources :students
    resources :instructors
  end

  resources :courses do
    resources :students
    resources :instructors
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  validates :student_ids, length: {maximum: 10}
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController

  before_action :is_logged

  def new
    @cohort = Cohort.new
  end

  def create
    @cohort = Cohort.new(cohort_params)

    if @cohort.save
      redirect_to @cohort
    else
      render 'new'
    end
  end

  def edit
    @cohort = Cohort.find(params[:id])
  end

  def update
    @cohort = Cohort.find(params[:id])
    if @cohort.update(cohort_params)
      p 'cohort successfully updated'
      redirect_to @cohort
    else
      render 'edit'
    end
  end

  def index
    @cohorts = Cohort.all
  end

  def show
    @students = Student.all
    @instructors = Instructor.all
    @cohort = Cohort.find(params[:id])

    @cohort_students = []

    if @cohort.student_ids
      @cohort.student_ids.each do |student|
        stu = Student.where(id: student).first
        if stu.blank?
          flash[:notice] = "Some Students not found or removed"
        else
          @cohort_students << stu
        end
      end
    end

    if @cohort.instructor_id
      @cohort_instructor = Instructor.where(id: @cohort.instructor_id).first
      if @cohort_instructor.blank?
        flash[:notice] = "Instructor not found or removed"
      end
    end

  end

  def destroy
    @cohort = Cohort.find(params[:id])
    @cohort.destroy
    respond_to do |format|
      format.js {redirect_to cohorts_path}
    end
  end

  private

  def cohort_params
    params.require(:cohort).permit(:name,:start_date,:end_date)
  end

  def is_logged
    redirect_to root_path unless logged_in?
  end
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/views/cohorts/destroy.js.erb
$('.delete-cohort').bind('ajax:success',function(){
  console.log('Cohort Deleted Successfully')
});

app/views/cohorts/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <div id="god-container">
      <div id="admin-panel-nav">
        <i class="fab fa-joomla fa-4x"></i>
        <ul>
          <li><i class="fas fa-home fa-sm"></i> <%= link_to('Home', '/') %></li>
          <li><%= link_to('Instructors', '/instructors') %></li>
          <li><%= link_to('Cohorts', '/cohorts') %></li>
          <li><%= link_to('Courses', '/courses') %></li>
          <li><%= link_to('Students', '/students') %></li>
          <li><i class="fas fa-sign-out-alt"></i>  <%= link_to("Log Out",logout_path,method: :delete, data: {confirm: 'Are you sure?'}) %></li>
        </ul>
      </div>

      <div id="admin-panel-content">
        <h1>Edit a Cohort</h1>

        <%= form_for(@cohort) do |f| %>
          <label>Cohort Name:</label><br>
          <%= f.text_field :name, placeholder: 'Name',required:true %><br><br>
          <label>Start Date:</label><br>
          <%= f.date_field :start_date,required:true %><br><br>
          <label>End Date:</label><br>
          <%= f.date_field :end_date,required:true %><br><br>
          <%= f.submit 'Edit Cohort' %>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/cohorts/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <div id="god-container">
      <div id="admin-panel-nav">
        <i class="fab fa-joomla fa-4x"></i>
        <ul>
          <li><i class="fas fa-home fa-sm"></i> <%= link_to('Home', '/') %></li>
          <li><%= link_to('Instructors', '/instructors') %></li>
          <li id="selected-admin-link"><%= link_to('Cohorts', '/cohorts') %></li>
          <li><%= link_to('Courses', '/courses') %></li>
          <li><%= link_to('Students', '/students') %></li>
          <li><i class="fas fa-sign-out-alt"></i> <%= link_to("Log Out",logout_path,method: :delete, data: {confirm: 'Are you sure?'}) %></li>
        </ul>
      </div>

      <div id="admin-panel-content">
        <h1>All Cohorts</h1>

        <a class="btn btn-primary btn-warning" href="/cohorts/new">Add Cohort</a><br><br>

        <table class="table table-dark table-striped">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Name</th>
              <th scope="col">Start Date</th>
              <th scope="col">End Date</th>
            </tr>
          </thead>
          <tbody>
            <% @cohorts.sort.each do |cohort| %>
              <tr>
                <th scope="row"><%= cohort.id %></th>
                <td><%= link_to "#{cohort.name}", cohort %></td>
                <td><%= cohort.start_date.strftime("%b %d, %Y") %></td>
                <td><%= cohort.end_date.strftime("%b %d, %Y") %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </body>
</html>

app/views/cohorts/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <div id="god-container">
      <div id="admin-panel-nav">
        <i class="fab fa-joomla fa-4x"></i>
        <ul>
          <li><i class="fas fa-home fa-sm"></i> <%= link_to('Home', '/') %></li>
          <li><%= link_to('Instructors', '/instructors') %></li>
          <li><%= link_to('Cohorts', '/cohorts') %></li>
          <li><%= link_to('Courses', '/courses') %></li>
          <li><%= link_to('Students', '/students') %></li>
          <li><i class="fas fa-sign-out-alt"></i>  <%= link_to("Log Out",logout_path,method: :delete, data: {confirm: 'Are you sure?'}) %></li>
        </ul>
      </div>

      <div id="admin-panel-content">
        <h1>Create a new Cohort</h1>

        <%= form_for(@cohort) do |f| %>
          <label>Cohort Name:</label><br>
          <%= f.text_field :name, placeholder: 'Name' %><br><br>
          <label>Start Date:</label><br>
          <%= f.date_field :start_date %><br><br>
          <label>End Date:</label><br>
          <%= f.date_field :end_date %><br><br>
          <%= f.submit 'Create Cohort' %>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/cohorts/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <div id="god-container">
      <div id="admin-panel-nav">
        <i class="fab fa-joomla fa-4x"></i>
        <ul>
          <li><i class="fas fa-home fa-sm"></i> <%= link_to('Home', '/') %></li>
          <li><%= link_to('Instructors', '/instructors') %></li>
          <li><%= link_to('Cohorts', '/cohorts') %></li>
          <li><%= link_to('Courses', '/courses') %></li>
          <li><%= link_to('Students', '/students') %></li>
          <li><i class="fas fa-sign-out-alt"></i>  <%= link_to("Log Out",logout_path,method: :delete, data: {confirm: 'Are you sure?'}) %></li>
        </ul>
      </div>

      <div id="admin-panel-content">
        <h1>Cohort: <%= @cohort.name %></h1>
        <h3><%= @cohort.start_date.strftime("Start Date: %b %d, %Y") %></h3>
        <h3><%= @cohort.end_date.strftime("End Date: %b %d, %Y") %></h3>
        <button type="button" class="btn btn-primary btn-warning" data-toggle="modal" data-target="#allInstructorsModal">
          Set Cohort Instructor
        </button>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary btn-warning" data-toggle="modal" data-target="#allStudentsModal">
          Add Students to Cohort
        </button>
        <a class="btn btn-primary btn-warning" href="/cohorts/<%=params[:id]%>/edit">Edit Cohort</a>
        <a data-confirm="Are you sure?" data-remote="true" class="delete-cohort btn btn-primary btn-warning" rel="nofollow" data-method="delete" href="/cohorts/<%=params[:id]%>">Delete Cohort</a><br><br><br>

        <% if @cohort_instructor %>
        <h2>Cohort Instructor: <%= @cohort_instructor.first_name %> <%= @cohort_instructor.last_name %></h2><br><br>
        <% end %>

        <% if @cohort_students.length > 0 %>

        <h2>Cohort Students</h2>

        <table class="table table-dark table-striped">
          <thead>
            <tr>
              <th scope="col">First</th>
              <th scope="col">Last</th>
              <th scope="col">Age</th>
              <th scope="col">Education</th>
            </tr>
          </thead>
          <tbody>
            <% @cohort_students.each do |student| %>
              <tr>
                <td><%= student.first_name %></td>
                <td><%= student.last_name %></td>
                <td><%= student.age %></td>
                <td><%= student.education %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <% end %>

        <!-- Modal -->
        <div class="modal fade" id="allStudentsModal" tabindex="-1" role="dialog" aria-labelledby="allStudentsModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header bg-dark text-warning">
                <h5 class="modal-title" id="allStudentsModalLabel"><strong>All Students</strong></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <table class="table table-dark table-striped">
                  <thead>
                    <tr>
                      <th scope="col">First</th>
                      <th scope="col">Last</th>
                      <th scope="col">Age</th>
                      <th scope="col">Education</th>
                      <th scope="col">Add to Cohort</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @students.each do |student| %>
                      <tr>
                        <td><%= student.first_name %></td>
                        <td><%= student.last_name %></td>
                        <td><%= student.age %></td>
                        <td><%= student.education %></td>
                        <td><%= link_to("Add Student", cohort_student_path(@cohort.id,student.id)) %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
              <div class="modal-footer bg-dark">
                <button type="button" class="btn btn-secondary btn-warning" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="allInstructorsModal" tabindex="-1" role="dialog" aria-labelledby="allInstructorsModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header bg-dark text-warning">
                <h5 class="modal-title" id="allInstructorsModalLabel"><strong>All Instructors</strong></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <table class="table table-dark table-striped">
                  <thead>
                    <tr>
                      <th scope="col">First</th>
                      <th scope="col">Last</th>
                      <th scope="col">Age</th>
                      <th scope="col">Education</th>
                      <th scope="col">Add to Cohort</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @instructors.each do |instructor| %>
                      <tr>
                        <td><%= instructor.first_name %></td>
                        <td><%= instructor.last_name %></td>
                        <td><%= instructor.age %></td>
                        <td><%= instructor.education %></td>
                        <td><%= link_to("Set Instructor", cohort_instructor_path(@cohort.id,instructor.id)) %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
              <div class="modal-footer bg-dark">
                <button type="button" class="btn btn-secondary btn-warning" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>

      </div> <!-- Ends the "content" div -->
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>