config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"

  get 'courses/new'
  get 'courses/edit'
  get 'courses/show'
  get 'courses/index'

  get 'instructors/new'
  get 'instructors/edit'
  get 'instructors/index'
  get 'instructors/show'

  get 'cohorts/new'
  get 'cohorts/edit'
  get 'cohorts/index'
  get 'cohorts/show'

  get 'admins/new'
  get 'admins/edit'
  get 'admins/show'
  get 'admins/index'

  get 'tests/new'
  get 'tests/edit'
  get 'tests/show'
  get 'tests/index'

  get 'students/new'
  get 'students/edit'
  get 'students/show'
  get 'students/index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :admins

  resources :students do
    delete 'terminate' => 'students#destroy'
  end

  resources :instructors do
    delete 'terminate' => 'students#destroy'
  end

  resources :cohorts do
    delete 'terminate' => 'cohorts#destroy'
  end

  resources :courses do
    delete 'terminate' => 'courses#destroy'
  end

  resources :cohorts do
    resources :students
    resources :instructors
  end

  resources :courses do
    resources :students
    resources :instructors
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admins/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body id="body-container">
      <div id="god-container">
        <div id="admin-panel-nav">
          <i class="fab fa-joomla fa-4x"></i>
          <ul>
            <li id="selected-admin-link"><i class="fas fa-home fa-sm"></i> <%= link_to('Home', '/') %></li>
            <li><%= link_to('Instructors', '/instructors') %></li>
            <li><%= link_to('Cohorts', '/cohorts') %></li>
            <li><%= link_to('Courses', '/courses') %></li>
            <li><%= link_to('Students', '/students') %></li>
            <li><i class="fas fa-sign-out-alt"></i> <%= link_to("Log Out",logout_path,method: :delete, data: {confirm: 'Are you sure?'}) %></li>
          </ul>
        </div>
      <div id="admin-panel-content">
        <div class="logged-navbar" id="logged-navbar">
          <h3>NYCDA</h3>
        </div>

        <div id="logged-content">
          <i class="fas fa-unlock-alt fa-2x"></i><br><br>
          <h1>You are Logged In</h1><br>
          <%= link_to("Log Out",logout_path,method: :delete, data: {confirm: 'Are you sure?'}) %>
        </div>
      </div>
    </div>
  </body>
</html>

<!-- <!DOCTYPE html> <html> <head> <title>Admin Page</title> <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
crossorigin="anonymous"> </head> <body id="body-container"> <div id="logged-navbar"> <h3>NYCDA</h3> </div> <div id="logged-content"> <i class="fas fa-unlock-alt fa-2x"></i> <% if logged_in? %> <h1>You are Logged In</h1> <h3><%= link_to("View
Students",students_path)%></h3> <h3><%= link_to("View Cohorts",cohorts_path)%></h3> <%= link_to("Log Out",logout_path,method: :delete, data: {confirm: 'Are you sure?'}) %> <% else %> <h1>Log in to access panel</h1> <%= link_to("Log In",login_path) %>
<% end %> </div> </body> </html> -->

app/views/admins/new.html.erb
<!DOCTYPE html>
<html>

  <head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  </head>

  <body>
    <div id="login-navbar">
      <h3><%= link_to("NYCDA", root_path) %></h3>
    </div>

    <div id="login-content" class="register-form-content">
      <i class="fas fa-unlock-alt fa-2x"></i>
      <h1>Add a new admin</h1>
      <%= form_for(@admin) do |f| %>
      <label>Username:</label><br>
      <%= f.text_field :username, placeholder: "Username", required: true %><br><br>
      <label>Password:</label><br>
      <%= f.password_field :password, placeholder: "Password", minlength:8, maxlength:20, title:"Enter an Password between 8-20 characters", required: true %><br><br>
      <label>Confirm Password:</label><br>
      <%= f.password_field :password_confirmation, placeholder: 'Password', minlength:8, maxlength:20, title:"Enter an Password between 8-20 characters", required: true %><br><br>
      <label>You found the lock, now use the key:</label><br>
      <%= f.password_field :admin_key, placeholder: "Key", required: true %><br><br>
      <%= f.submit "Register" %>
      <% end %><br><br>
      Already have an account? <%= link_to("Log In", root_path)%><br><br>
    </div>
</body>

</html>